apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-kubernetes
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: debug-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debug-kubernetes
    spec:
      containers:
        - image: pyar6329/debug-kubernetes:5.0
          name: debug-kubernetes
          resources:
            limits:
              cpu: 10m
            requests:
              cpu: 10m
      restartPolicy: Always
status: {}
