apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-ubuntu
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: debug-ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debug-ubuntu
    spec:
      containers:
        - image: "ghcr.io/pyar6329/debug-kubernetes:7.0"
          name: debug-ubuntu
          resources:
            limits:
              cpu: 10m
            requests:
              cpu: 10m
      restartPolicy: Always
status: {}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: default
  name: debug-ubuntu
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: debug-ubuntu
